# -*- coding: utf-8 -*-
"""Student performance analytics system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqtESH4iF4eZzkvX4iejba_ZV5ht5hwt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Student_ID": range(101, 121),
    "Name": [
        "Aarav", "Priya", "Rahul", "Ananya", "Vikash",
        "Neha", "Rohan", "Sneha", "Aman", "Kavya",
        "Arjun", "Pooja", "Aditya", "Simran", "Karan",
        "Isha", "Mohit", "Nisha", "Sahil", "Riya"
    ],
    "Department": ["CSE"] * 20,
    "Python": [82, 75, 91, 68, 55, 88, 72, 95, 61, 79,
               84, 67, 93, 58, 76, 89, 64, 81, 70, 97],
    "NumPy": [78, 81, 89, 72, 59, 92, 70, 94, 65, 75,
              86, 62, 90, 61, 73, 91, 68, 79, 74, 96],
    "Pandas": [85, 79, 94, 70, 57, 90, 75, 96, 63, 82,
               88, 65, 92, 60, 78, 87, 66, 84, 72, 98],
    "AI": [80, 83, 92, 74, 61, 89, 73, 97, 68, 78,
           85, 69, 95, 64, 80, 90, 70, 82, 76, 99],
    "Attendance": [92, 88, 95, 82, 76, 94, 85, 98, 79, 90,
                   93, 80, 96, 74, 87, 91, 78, 89, 84, 99]
}
df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)
display(df)

print("students.csv created successfully!")

df = pd.read_csv("students.csv")
print("Student Data:")
display(df)

from google.colab import files
files.download("students.csv")

print("Number of students:", len(df))
print("\nColumns:")
print(df.columns.tolist())
print("\nDataset Information:")
df.info()

print("Basic Statistics:")
display(df.describe())

subjects = ["Python", "NumPy", "Pandas", "AI"]
print("Subjects:", subjects)

df["Total"] = df[subjects].sum(axis=1)
print("Total marks calculated:")
display(df[["Student_ID", "Name", "Total"]])

df["Average"] = df[subjects].mean(axis=1)
print("Average marks calculated:")
display(df[["Student_ID", "Name", "Average"]])

def assign_grade(average):
 if average >= 90:
  return "A+"
 elif average >= 80:
  return "A"
 elif average >= 70:
  return "B"
 elif average >= 60:
  return "C"
 elif average >= 50:
  return "D"
 else:
  return "F"
df["Grade"] = df["Average"].apply(assign_grade)

print("Grades assigned:")
display(df[["Student_ID", "Name", "Average", "Grade"]])

def pass_fail(row):
    marks = row[subjects].to_numpy(dtype=float)

    if np.all(marks >= 40):
        return "Pass"
    else:
        return "Fail"

df["Result"] = df.apply(pass_fail, axis=1)

print("Pass/Fail Status:")
display(df[["Student_ID", "Name", "Result"]])

from IPython.display import display

print("Complete Student Analysis:")

display(
    df[
        [
            "Student_ID",
            "Name",
            "Department",
            "Python",
            "NumPy",
            "Pandas",
            "AI",
            "Attendance",
            "Total",
            "Average",
            "Grade",
            "Result"
        ]
    ]
)

import numpy as np

print("===== CLASS SUMMARY =====")

print("Number of students:", len(df))
print("Overall class average:", round(np.mean(df["Average"]), 2))
print("Highest average:", round(np.max(df["Average"]), 2))
print("Lowest average:", round(np.min(df["Average"]), 2))
print("Passed students:", (df["Result"] == "Pass").sum())
print("Failed students:", (df["Result"] == "Fail").sum())

subjects = ["Python", "NumPy", "Pandas", "AI"]

subject_avg = df[subjects].mean()

print("===== SUBJECT-WISE AVERAGE =====")
display(subject_avg.round(2))

print("Best subject:", subject_avg.idxmax())
print("Lowest average subject:", subject_avg.idxmin())

subjects = ["Python", "NumPy", "Pandas", "AI"]
marks_array = df[subjects].to_numpy()

print("===== NUMPY ANALYSIS =====")
print("Overall marks average:", round(np.mean(marks_array), 2))
print("Highest individual subject mark:", np.max(marks_array))
print("Lowest individual subject mark:", np.min(marks_array))

top_students = df.nlargest(3, "Average")[["Student_ID", "Name", "Average", "Grade"]]

print("===== TOP 3 PERFORMERS =====")
display(top_students)

grade_distribution = df["Grade"].value_counts().sort_index()

print("===== GRADE DISTRIBUTION =====")
display(grade_distribution)

result_distribution = df["Result"].value_counts()

print("===== PASS / FAIL DISTRIBUTION =====")
display(result_distribution)

highest_student = df.loc[df["Average"].idxmax()]

print("===== HIGHEST PERFORMER =====")
print("Student ID:", highest_student["Student_ID"])
print("Name:", highest_student["Name"])
print("Average:", round(highest_student["Average"], 2))
print("Grade:", highest_student["Grade"])

lowest_student = df.loc[df["Average"].idxmin()]

print("===== LOWEST PERFORMER =====")
print("Student ID:", lowest_student["Student_ID"])
print("Name:", lowest_student["Name"])
print("Average:", round(lowest_student["Average"], 2))
print("Grade:", lowest_student["Grade"])

plt.figure(figsize=(8, 5))
subject_avg.plot(kind="bar")

plt.title("Subject-wise Average Marks")
plt.xlabel("Subject")
plt.ylabel("Average Marks")
plt.xticks(rotation=0)
plt.tight_layout()

plt.savefig("subject_average.png", dpi=300, bbox_inches="tight")
plt.show()



plt.figure(figsize=(8, 5))
grade_distribution.plot(kind="bar")

plt.title("Grade Distribution")
plt.xlabel("Grade")
plt.ylabel("Number of Students")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("grade_distribution.png")
plt.show()

plt.figure(figsize=(10, 5))

plt.bar(df["Name"], df["Average"])

plt.title("Student Average Performance")
plt.xlabel("Student")
plt.ylabel("Average Marks")
plt.xticks(rotation=60)

plt.tight_layout()
plt.savefig("student_average.png")
plt.show()

df.to_csv(
    "student_performance_analysis.csv",
    index=False
)

print("Final analysis saved successfully.")
print("File: student_performance_analysis.csv")

print("================================================")
print("     STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("================================================")

print("\n===== CLASS SUMMARY =====")
print("Number of students:", len(df))
print("Overall class average:", round(df["Average"].mean(), 2))
print("Highest average:", round(df["Average"].max(), 2))
print("Lowest average:", round(df["Average"].min(), 2))
print("Passed students:", (df["Result"] == "Pass").sum())
print("Failed students:", (df["Result"] == "Fail").sum())

print("\n===== SUBJECT-WISE AVERAGE =====")
for subject, average in subject_avg.items():
    print(subject, ":", round(average, 2))

print("Best subject:", subject_avg.idxmax())
print("Lowest average subject:", subject_avg.idxmin())

print("\n===== TOP 3 PERFORMERS =====")
print(top_students.to_string(index=False))

print("\n===== GRADE DISTRIBUTION =====")
print(grade_distribution)

print("\n===== NUMPY ANALYSIS =====")
print("Overall marks average:", round(np.mean(marks_array), 2))
print("Highest individual subject mark:", np.max(marks_array))
print("Lowest individual subject mark:", np.min(marks_array))

print("================================================")

